# Generated by Django 2.2 on 2019-06-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_variation_category'),
        ('cart', '0004_cartitem_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variation',
            field=models.ManyToManyField(to='menu.Variation'),
        ),
    ]
