# Generated by Django 2.2 on 2019-05-16 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20190515_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portofolio_site',
        ),
    ]
