# Generated by Django 2.2 on 2019-05-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_userprofileinfo_portofolio_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='Kecamatan',
            field=models.TextField(default='tidak Diketahui', max_length=64),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='Kelurahan',
            field=models.TextField(default='tidak Diketahui', max_length=64),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='Kota',
            field=models.TextField(default='tidak Diketahui', max_length=64),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='Provinsi',
            field=models.TextField(default='tidak Diketahui', max_length=64),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='address1',
            field=models.CharField(default='tidak Diketahui', max_length=128),
        ),
    ]
