# Generated by Django 2.2 on 2019-05-17 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20190516_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='slug',
            field=models.SlugField(default='product-'),
        ),
        migrations.AddField(
            model_name='menu',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 17, 13, 12, 43, 950146)),
        ),
        migrations.AddField(
            model_name='menu',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 17, 13, 12, 43, 950146)),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='Kecamatan',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='Kelurahan',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='Kota',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='Provinsi',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='address1',
            field=models.TextField(max_length=128),
        ),
    ]
