# Generated by Django 2.2 on 2019-05-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20190517_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
