# Generated by Django 2.2 on 2019-05-19 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_bannerhome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannerhome',
            old_name='BannerHome',
            new_name='Banner_Home',
        ),
    ]
