# Generated by Django 2.2 on 2019-06-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_variation_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='coba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
    ]
