# Generated by Django 2.2 on 2019-06-24 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_coba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='coba',
        ),
    ]
