# Generated by Django 2.2 on 2019-06-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_delete_coba'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='pria',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='wanita',
            field=models.BooleanField(default=False),
        ),
    ]
