# Generated by Django 2.2 on 2019-06-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_auto_20190624_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='pria',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='wanita',
        ),
        migrations.AddField(
            model_name='menu',
            name='JK',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
