# Generated by Django 2.2 on 2019-06-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_auto_20190624_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.SlugField(default='product-', unique=True),
        ),
    ]
