# Generated by Django 2.2 on 2019-06-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_auto_20190627_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.SlugField(default='product-'),
        ),
    ]
