# Generated by Django 2.2 on 2019-06-27 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0018_auto_20190627_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.SlugField(default='random_number'),
        ),
    ]
