# Generated by Django 2.2 on 2019-06-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0019_auto_20190627_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.SlugField(default='HE3OG8'),
        ),
    ]
