# Generated by Django 2.2 on 2019-06-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0021_auto_20190627_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.SlugField(default='product-', unique=True),
        ),
    ]
