# Generated by Django 2.2 on 2019-07-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0022_auto_20190628_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='kuantitas',
            field=models.IntegerField(default=0),
        ),
    ]
