# Generated by Django 2.2 on 2019-07-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0023_userprofileinfo_kuantitas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='kuantitas',
        ),
        migrations.AddField(
            model_name='menu',
            name='kuantitas',
            field=models.IntegerField(default=0),
        ),
    ]
