# Generated by Django 2.2 on 2019-07-07 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0024_auto_20190703_2226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaksi',
        ),
    ]
