# Generated by Django 2.2 on 2019-07-07 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0025_delete_transaksi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='address1',
            new_name='alamat',
        ),
    ]
