# Generated by Django 2.2 on 2019-07-07 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0026_auto_20190707_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='harga',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='image',
        ),
    ]
