# Generated by Django 2.2.3 on 2019-07-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0027_auto_20190707_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='diskon',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='menu',
            name='hargaMenu',
            field=models.IntegerField(default=0),
        ),
    ]
