# Generated by Django 2.2.3 on 2019-07-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0028_auto_20190713_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='posterMenu',
            field=models.ImageField(blank=True, upload_to='menu/img/poster'),
        ),
    ]
