# Generated by Django 2.2 on 2020-09-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0029_menu_postermenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='menu',
            name='posterMenu',
            field=models.ImageField(blank=True, upload_to='menu/img/'),
        ),
    ]
