# Generated by Django 2.2 on 2020-09-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0030_auto_20200920_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='JK',
            field=models.CharField(blank='True', default=1, max_length=100),
        ),
    ]
