# Generated by Django 2.2 on 2020-09-20 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0031_auto_20200920_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='JK',
        ),
    ]
