# Generated by Django 2.2 on 2020-09-20 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0032_remove_menu_jk'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menu.Category'),
            preserve_default=False,
        ),
    ]
