# Generated by Django 2.2 on 2020-09-20 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0033_menu_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='category',
        ),
    ]
