# Generated by Django 2.2 on 2020-09-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0035_menu_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_pic',
            field=models.ImageField(blank=True, upload_to='menu/img/'),
        ),
    ]
