# Generated by Django 2.2 on 2019-06-26 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_order_buktipembayaran'),
    ]

    operations = [
        migrations.CreateModel(
            name='buktiPembayaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='test', max_length=120, unique=True)),
                ('buktiPembayaran', models.FileField(blank=True, upload_to='bukti_pembayaran/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
