# Generated by Django 2.2 on 2019-06-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_buktipembayaran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buktipembayaran',
            name='user',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
