# Generated by Django 2.2 on 2019-06-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20190626_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buktipembayaran',
            name='order_id',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
