# Generated by Django 2.2 on 2019-06-28 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
