# Generated by Django 2.2 on 2019-06-30 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_delete_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='final_total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ongkir_total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sub_total',
        ),
    ]
