# Generated by Django 2.2 on 2019-07-07 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20190630_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buktiPembayaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.buktiPembayaran'),
        ),
    ]
