# Generated by Django 2.2 on 2019-07-07 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20190708_0002'),
    ]

    operations = [
        migrations.DeleteModel(
            name='buktiPembayaran',
        ),
    ]
